### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by gannon93** [gannon93/gkit_cogs#2]
The following is my tentative road map for the future of gkit_cogs.

## General

  - [ ] General code cleanup and improvement in quality.
  - [ ] Test cogs.

### FlavorSavor 

  - [ ] Implement `bitter` command.
  - [ ] Implement `gusto` command.
  - [ ] Implement `juicy` command.
  - [ ] Implement `salty` command.
  - [ ] Implement `sour` command.
  - [ ] Implement `spicy` command.
  - [ ] Implement `sweet` command.
  - [ ] Implement `umami` command.

### SaltyDebt
  - [ ] Implement `balance` command.
  - [ ] Implement `bet` command.
  - [ ] Implement `cashout` command.

### WannaCookie
